# Generated by Django 5.2.7 on 2026-04-04 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("SQLITE", "SQLite"),
                            ("INFRADB", "InfraDB Native"),
                            ("POSTGRES", "PostgreSQL"),
                            ("MYSQL", "MySQL"),
                            ("SNOWFLAKE", "Snowflake"),
                        ],
                        default="INFRADB",
                        max_length=50,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.IntegerField(default=0)),
                ("database_name", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="databases.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemaMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("column_name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=100)),
                ("is_nullable", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="databases.databaseconnection",
                    ),
                ),
            ],
            options={
                "unique_together": {("connection", "table_name", "column_name")},
            },
        ),
    ]
