# Generated by Django 5.2.7 on 2025-11-11 01:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("db_type", models.CharField(max_length=32)),
                ("mode", models.CharField(default="local", max_length=32)),
                ("node", models.CharField(blank=True, max_length=255, null=True)),
                ("config_encrypted", models.TextField(blank=True, null=True)),
                ("result_encrypted", models.TextField(blank=True, null=True)),
                (
                    "container_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("provisioning", "Provisioning"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("logs", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
