# Generated by Django 5.2.7 on 2025-12-09 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploydb", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="deployment",
            old_name="name",
            new_name="db_name",
        ),
        migrations.RenameField(
            model_name="deployment",
            old_name="config_encrypted",
            new_name="result",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="container_id",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="logs",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="node",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="result_encrypted",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="deployment",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="host",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="deployment",
            name="port",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="deployment",
            name="user_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="id",
            field=models.UUIDField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="status",
            field=models.CharField(default="pending", max_length=32),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
