# Generated by Django 5.2.7 on 2025-12-09 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploydb", "0002_rename_name_deployment_db_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
