# Generated by Django 5.2.7 on 2025-10-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_queryhistory_delete_savedquery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queryhistory",
            old_name="sql",
            new_name="query",
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="name",
        ),
    ]
