# Generated by Django 5.2.7 on 2025-10-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_sql_queryhistory_query_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="db_type",
            field=models.CharField(default="sqlite", max_length=50),
        ),
        migrations.AddField(
            model_name="queryhistory",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
