# Generated by Django 5.2.7 on 2025-10-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_queryhistory_db_type_queryhistory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queryhistory",
            name="db_type",
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="name",
        ),
    ]
